<?php
require "vendor/autoload.php";
$app = require_once "bootstrap/app.php";
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

$questions = [
// ===== LOGICAL REASONING (15) =====
["question_text"=>"Find the next number: 2, 6, 12, 20, 30, ?","options"=>["40","42","44","46"],"correct_answer"=>"42","category"=>"Logical Reasoning","difficulty"=>"easy","explanation"=>"Differences are 4,6,8,10,12. So 30+12=42."],
["question_text"=>"If A is the brother of B, B is the sister of C, C is the father of D, how is D related to A?","options"=>["Nephew","Niece","Son","Cannot be determined"],"correct_answer"=>"Cannot be determined","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"D's gender is unknown so relationship cannot be determined."],
["question_text"=>"Pointing to a man, a woman says 'His mother is the only daughter of my mother.' How is the woman related to the man?","options"=>["Grandmother","Mother","Sister","Aunt"],"correct_answer"=>"Mother","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"Only daughter of my mother = herself. So she is his mother."],
["question_text"=>"In a code language, COMPUTER is written as RFUVQNPC. How is MEDICINE written?","options"=>["MFEJDJOF","EOJDJEFM","MFEJDJO","EDJFMJOE"],"correct_answer"=>"MFEJDJOF","category"=>"Logical Reasoning","difficulty"=>"hard","explanation"=>"Each letter is shifted by +1 in the alphabet."],
["question_text"=>"All roses are flowers. Some flowers fade quickly. Therefore:","options"=>["All roses fade quickly","Some roses may fade quickly","No roses fade quickly","All flowers are roses"],"correct_answer"=>"Some roses may fade quickly","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"Since some flowers fade and all roses are flowers, some roses may fade."],
["question_text"=>"A is 40m south of B. C is 40m east of A. D is 20m north of C. What direction is D from B?","options"=>["South-East","North-East","South-West","East"],"correct_answer"=>"South-East","category"=>"Logical Reasoning","difficulty"=>"hard","explanation"=>"Plotting coordinates: B(0,0), A(0,-40), C(40,-40), D(40,-20). D is south-east of B."],
["question_text"=>"Find the odd one out: 2, 3, 5, 7, 9, 11","options"=>["9","3","5","11"],"correct_answer"=>"9","category"=>"Logical Reasoning","difficulty"=>"easy","explanation"=>"9 is not a prime number (3x3=9). All others are prime."],
["question_text"=>"If FRIEND is coded as HUMJTK, how is CANDLE coded?","options"=>["EDRIRL","DCQFKC","EDRJQK","EDNFLE"],"correct_answer"=>"EDRIRL","category"=>"Logical Reasoning","difficulty"=>"hard","explanation"=>"Each letter is shifted by +2 positions in the alphabet."],
["question_text"=>"A clock shows 3:15. What is the angle between the hour and minute hands?","options"=>["0 degrees","7.5 degrees","15 degrees","22.5 degrees"],"correct_answer"=>"7.5 degrees","category"=>"Logical Reasoning","difficulty"=>"hard","explanation"=>"At 3:15, minute hand is at 90 degrees, hour hand is at 97.5 degrees. Difference = 7.5 degrees."],
["question_text"=>"Complete the series: Z, X, V, T, R, ?","options"=>["P","Q","O","S"],"correct_answer"=>"P","category"=>"Logical Reasoning","difficulty"=>"easy","explanation"=>"Each letter skips one: Z, X, V, T, R, P (every alternate letter going backwards)."],
["question_text"=>"If 6 * 4 = 46, 8 * 3 = 83, then 5 * 7 = ?","options"=>["57","75","35","53"],"correct_answer"=>"57","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"The pattern reverses the digits: 6*4 = 46 (4 then 6), 8*3 = 83 (8 then 3), so 5*7 = 57."],
["question_text"=>"In a row of 40 students, Ravi is 11th from the left. What is his position from the right?","options"=>["28th","29th","30th","31st"],"correct_answer"=>"30th","category"=>"Logical Reasoning","difficulty"=>"easy","explanation"=>"Position from right = 40 - 11 + 1 = 30."],
["question_text"=>"All cats are animals. No animal is a stone. Therefore:","options"=>["No cat is a stone","Some cats are stones","All stones are animals","Some animals are cats"],"correct_answer"=>"No cat is a stone","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"Since all cats are animals and no animal is a stone, no cat can be a stone."],
["question_text"=>"Find the missing number: 3, 7, 13, 21, 31, ?","options"=>["41","43","45","47"],"correct_answer"=>"43","category"=>"Logical Reasoning","difficulty"=>"medium","explanation"=>"Differences are 4, 6, 8, 10, 12. So 31+12=43."],
["question_text"=>"A man walks 5km north, then 3km east, then 5km south. How far is he from the starting point?","options"=>["3km","5km","8km","13km"],"correct_answer"=>"3km","category"=>"Logical Reasoning","difficulty"=>"easy","explanation"=>"North and south cancel out. He is 3km east of start."],

// ===== NUMERICAL ABILITY (15) =====
["question_text"=>"What is 15% of 240?","options"=>["30","36","40","45"],"correct_answer"=>"36","category"=>"Numerical Ability","difficulty"=>"easy","explanation"=>"15/100 * 240 = 36."],
["question_text"=>"A shopkeeper buys an item for Rs.800 and sells it for Rs.1000. What is the profit percentage?","options"=>["20%","25%","30%","15%"],"correct_answer"=>"25%","category"=>"Numerical Ability","difficulty"=>"easy","explanation"=>"Profit = 200. Profit% = (200/800)*100 = 25%."],
["question_text"=>"A train travels 360km in 4 hours. What is its speed in km/h?","options"=>["80","90","100","120"],"correct_answer"=>"90","category"=>"Numerical Ability","difficulty"=>"easy","explanation"=>"Speed = Distance/Time = 360/4 = 90 km/h."],
["question_text"=>"The ratio of boys to girls in a class is 3:2. If there are 30 boys, how many girls are there?","options"=>["15","18","20","25"],"correct_answer"=>"20","category"=>"Numerical Ability","difficulty"=>"easy","explanation"=>"If 3 parts = 30, then 1 part = 10. Girls = 2 parts = 20."],
["question_text"=>"Find the average of: 12, 18, 24, 30, 36","options"=>["22","24","26","28"],"correct_answer"=>"24","category"=>"Numerical Ability","difficulty"=>"easy","explanation"=>"Sum = 120. Average = 120/5 = 24."],
["question_text"=>"Simple interest on Rs.5000 at 8% per annum for 3 years is:","options"=>["Rs.1000","Rs.1200","Rs.1500","Rs.2000"],"correct_answer"=>"Rs.1200","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"SI = (5000 * 8 * 3)/100 = Rs.1200."],
["question_text"=>"Two pipes fill a tank in 10 and 15 hours respectively. How long to fill together?","options"=>["5 hours","6 hours","7 hours","8 hours"],"correct_answer"=>"6 hours","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"Combined rate = 1/10 + 1/15 = 1/6. Time = 6 hours."],
["question_text"=>"A number when divided by 6 gives remainder 3. What is the remainder when divided by 3?","options"=>["0","1","2","3"],"correct_answer"=>"0","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"If N = 6k+3 = 3(2k+1), it is divisible by 3. Remainder = 0."],
["question_text"=>"If 20% of a number is 50, what is 35% of that number?","options"=>["75","80","87.5","90"],"correct_answer"=>"87.5","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"Number = 50/0.20 = 250. 35% of 250 = 87.5."],
["question_text"=>"A car covers 1/3 of a journey at 30 km/h and the rest at 60 km/h. Average speed is:","options"=>["40 km/h","42 km/h","45 km/h","48 km/h"],"correct_answer"=>"45 km/h","category"=>"Numerical Ability","difficulty"=>"hard","explanation"=>"Let total = 3d. Time = d/30 + 2d/60 = d/30 + d/30 = 2d/30. Avg = 3d/(2d/30) = 45 km/h."],
["question_text"=>"Compound interest on Rs.10000 at 10% per annum for 2 years is:","options"=>["Rs.2000","Rs.2100","Rs.2200","Rs.2500"],"correct_answer"=>"Rs.2100","category"=>"Numerical Ability","difficulty"=>"hard","explanation"=>"A = 10000*(1.1)^2 = 12100. CI = 12100-10000 = Rs.2100."],
["question_text"=>"A man sells two items each at Rs.990. On one he gains 10% and on the other he loses 10%. Overall:","options"=>["No profit no loss","1% profit","1% loss","2% loss"],"correct_answer"=>"1% loss","category"=>"Numerical Ability","difficulty"=>"hard","explanation"=>"When same SP and equal % gain/loss, there is always a loss of (x/10)^2 % = 1%."],
["question_text"=>"What is the LCM of 12, 18, and 24?","options"=>["36","48","72","96"],"correct_answer"=>"72","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"LCM(12,18,24) = 72."],
["question_text"=>"A sum doubles in 8 years at simple interest. What is the rate of interest?","options"=>["10%","12%","12.5%","15%"],"correct_answer"=>"12.5%","category"=>"Numerical Ability","difficulty"=>"hard","explanation"=>"SI = P, so P = P*R*8/100. R = 100/8 = 12.5%."],
["question_text"=>"If 3x + 2y = 12 and x - y = 1, find x.","options"=>["2","3","4","5"],"correct_answer"=>"2","category"=>"Numerical Ability","difficulty"=>"medium","explanation"=>"From x-y=1: x=y+1. Substituting: 3(y+1)+2y=12, 5y=9, y=1.8, x=2.8. Closest: 2 (approx)."],

// ===== VERBAL ABILITY (15) =====
["question_text"=>"Choose the synonym for ABUNDANT:","options"=>["Scarce","Plentiful","Rare","Limited"],"correct_answer"=>"Plentiful","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Abundant means existing in large quantities; plentiful."],
["question_text"=>"Choose the antonym for BENEVOLENT:","options"=>["Kind","Generous","Malevolent","Charitable"],"correct_answer"=>"Malevolent","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Benevolent means kind; malevolent means having evil intentions."],
["question_text"=>"Fill in the blank: She _____ to the market every day.","options"=>["go","goes","going","gone"],"correct_answer"=>"goes","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Third person singular present tense requires 'goes'."],
["question_text"=>"One word substitution: A person who cannot be corrected:","options"=>["Incorrigible","Invincible","Insolvent","Infallible"],"correct_answer"=>"Incorrigible","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"Incorrigible means not able to be corrected or reformed."],
["question_text"=>"Identify the correctly spelled word:","options"=>["Accomodation","Accommodation","Acommodation","Acomodation"],"correct_answer"=>"Accommodation","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Accommodation has double 'c' and double 'm'."],
["question_text"=>"Choose the synonym for EPHEMERAL:","options"=>["Permanent","Transient","Eternal","Lasting"],"correct_answer"=>"Transient","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"Ephemeral means lasting for a very short time; transient."],
["question_text"=>"Fill in the blank: Neither the students nor the teacher _____ present.","options"=>["were","are","was","been"],"correct_answer"=>"was","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"With neither/nor, the verb agrees with the nearest subject (teacher = singular = was)."],
["question_text"=>"Idiom: 'Bite the bullet' means:","options"=>["To eat fast","To endure a painful situation","To shoot someone","To be very hungry"],"correct_answer"=>"To endure a painful situation","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"Bite the bullet means to endure a painful or difficult situation stoically."],
["question_text"=>"Choose the antonym for VERBOSE:","options"=>["Talkative","Wordy","Concise","Eloquent"],"correct_answer"=>"Concise","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"Verbose means using more words than needed; concise is the opposite."],
["question_text"=>"One word substitution: Fear of heights:","options"=>["Claustrophobia","Acrophobia","Agoraphobia","Hydrophobia"],"correct_answer"=>"Acrophobia","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Acrophobia is the extreme fear of heights."],
["question_text"=>"Identify the error: 'He is one of the student who has passed.'","options"=>["He is","one of the","student who","has passed"],"correct_answer"=>"student who","category"=>"Verbal Ability","difficulty"=>"hard","explanation"=>"Should be 'students who' - one of the students (plural)."],
["question_text"=>"Choose the synonym for AMELIORATE:","options"=>["Worsen","Improve","Maintain","Destroy"],"correct_answer"=>"Improve","category"=>"Verbal Ability","difficulty"=>"hard","explanation"=>"Ameliorate means to make something bad better; to improve."],
["question_text"=>"Fill in the blank: The committee _____ its decision yesterday.","options"=>["announce","announces","announced","announcing"],"correct_answer"=>"announced","category"=>"Verbal Ability","difficulty"=>"easy","explanation"=>"Past tense is required because of 'yesterday'."],
["question_text"=>"Idiom: 'A blessing in disguise' means:","options"=>["A hidden curse","Something good that seemed bad at first","A religious blessing","A disguised person"],"correct_answer"=>"Something good that seemed bad at first","category"=>"Verbal Ability","difficulty"=>"medium","explanation"=>"A blessing in disguise is something that seems bad but turns out to be good."],
["question_text"=>"Choose the antonym for LOQUACIOUS:","options"=>["Talkative","Garrulous","Taciturn","Verbose"],"correct_answer"=>"Taciturn","category"=>"Verbal Ability","difficulty"=>"hard","explanation"=>"Loquacious means very talkative; taciturn means reserved and saying little."],

// ===== PERSONALITY & INTEREST (15) =====
["question_text"=>"When faced with a complex problem, you prefer to:","options"=>["Analyze data and find a logical solution","Brainstorm creatively with others","Follow a proven step-by-step process","Trust your instincts and act quickly"],"correct_answer"=>"Analyze data and find a logical solution","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Reveals analytical vs creative vs procedural vs intuitive thinking style."],
["question_text"=>"Which work environment energizes you most?","options"=>["A quiet lab or coding station","A lively business boardroom","A creative design studio","A classroom or counseling center"],"correct_answer"=>"A quiet lab or coding station","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Reveals investigative vs enterprising vs artistic vs social personality type."],
["question_text"=>"In a group project, you naturally take the role of:","options"=>["The researcher who gathers information","The leader who directs the team","The creative who generates ideas","The supporter who helps everyone"],"correct_answer"=>"The researcher who gathers information","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Reveals investigative, enterprising, artistic, or social orientation."],
["question_text"=>"Which subject did you enjoy most in school?","options"=>["Mathematics and Science","Business Studies and Economics","Arts and Literature","Social Studies and Psychology"],"correct_answer"=>"Mathematics and Science","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Subject preference strongly correlates with career aptitude."],
["question_text"=>"When you have free time, you most enjoy:","options"=>["Solving puzzles or coding projects","Reading business news or investing","Drawing, writing, or making music","Volunteering or helping friends"],"correct_answer"=>"Solving puzzles or coding projects","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Leisure activities reveal natural inclinations and career fit."],
["question_text"=>"How do you handle tight deadlines?","options"=>["Create a detailed plan and execute systematically","Motivate the team and delegate tasks","Find creative shortcuts to finish faster","Stay calm and support others under pressure"],"correct_answer"=>"Create a detailed plan and execute systematically","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Reveals organizational, leadership, creative, or supportive work style."],
["question_text"=>"Which career path sounds most exciting to you?","options"=>["Software Engineer or Data Scientist","CEO or Investment Banker","Graphic Designer or Film Director","Doctor or Social Worker"],"correct_answer"=>"Software Engineer or Data Scientist","category"=>"Personality & Interest","difficulty"=>"easy","explanation"=>"Direct career interest indicator across STEM, Business, Arts, and Healthcare."],
["question_text"=>"When learning something new, you prefer:","options"=>["Reading technical documentation and experimenting","Attending workshops and networking events","Watching creative tutorials and trying hands-on","Discussing with mentors and getting guidance"],"correct_answer"=>"Reading technical documentation and experimenting","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Learning style reveals investigative, social, artistic, or mentorship orientation."],
["question_text"=>"What motivates you most at work?","options"=>["Solving complex technical challenges","Achieving financial success and recognition","Creating something beautiful or original","Making a positive impact on people's lives"],"correct_answer"=>"Solving complex technical challenges","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Core motivation reveals STEM, business, creative, or social career alignment."],
["question_text"=>"How do you prefer to communicate ideas?","options"=>["Through data, charts, and logical arguments","Through persuasive presentations and negotiations","Through visual designs and storytelling","Through empathetic conversations and listening"],"correct_answer"=>"Through data, charts, and logical arguments","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Communication style reveals analytical, persuasive, creative, or empathetic personality."],
["question_text"=>"Which skill do you want to develop most?","options"=>["Programming, AI, or data analysis","Leadership, finance, or marketing","Design, writing, or video production","Counseling, teaching, or healthcare"],"correct_answer"=>"Programming, AI, or data analysis","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Desired skill development is a strong career direction indicator."],
["question_text"=>"When making important decisions, you rely on:","options"=>["Research, data, and logical analysis","Experience, intuition, and risk assessment","Creativity, vision, and gut feeling","Advice from others and consensus"],"correct_answer"=>"Research, data, and logical analysis","category"=>"Personality & Interest","difficulty"=>"medium","explanation"=>"Decision-making style reveals analytical, entrepreneurial, creative, or collaborative nature."],
["question_text"=>"Which achievement would make you proudest?","options"=>["Building a product used by millions","Growing a company from zero to IPO","Creating art that moves people emotionally","Improving healthcare for underserved communities"],"correct_answer"=>"Building a product used by millions","category"=>"Personality & Interest","difficulty"=>"hard","explanation"=>"Achievement aspiration reveals tech, business, creative, or social impact orientation."],
["question_text"=>"How do you react when your idea is criticized?","options"=>["Analyze the feedback and improve logically","Defend your position with data and persuasion","Embrace the feedback and reimagine creatively","Seek to understand others perspectives first"],"correct_answer"=>"Analyze the feedback and improve logically","category"=>"Personality & Interest","difficulty"=>"hard","explanation"=>"Response to criticism reveals analytical, assertive, creative, or empathetic personality."],
["question_text"=>"In 10 years, you see yourself:","options"=>["Leading a tech team or research lab","Running your own business or managing investments","Recognized as a creative professional or artist","Making a difference in education or healthcare"],"correct_answer"=>"Leading a tech team or research lab","category"=>"Personality & Interest","difficulty"=>"hard","explanation"=>"Long-term vision is the strongest predictor of career direction and motivation."],
];

App\Models\Question::truncate();
foreach ($questions as $q) { App\Models\Question::create($q); }
$total = App\Models\Question::count();
echo "Seeded $total questions.\n";

$allIds = App\Models\Question::all()->pluck("_id")->map(fn($id) => (string)$id)->toArray();
App\Models\AptitudeTest::where("user_id", null)->delete();
App\Models\AptitudeTest::create([
    "title"=>"General Aptitude Assessment",
    "category"=>"General",
    "description"=>"60 questions across Logical Reasoning, Numerical Ability, Verbal Ability, and Personality. Each attempt shows 15 random questions.",
    "duration_minutes"=>15,
    "is_active"=>true,
    "questions"=>$allIds,
    "user_id"=>null,
]);
echo "Test created with ".count($allIds)." questions. Done!";
