<?php
require "vendor/autoload.php";
$app = require_once "bootstrap/app.php";
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

// Add 50 interest/personality questions to the existing pool
$interestQuestions = [
["question_text"=>"Which subject excites you the most?","options"=>["Mathematics and Coding","Biology and Medicine","Business and Economics","Arts and Design"],"correct_answer"=>"Mathematics and Coding","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Subject preference reveals career domain alignment."],
["question_text"=>"What kind of problems do you enjoy solving?","options"=>["Technical and logical puzzles","Human health and wellness issues","Financial and market challenges","Creative and aesthetic problems"],"correct_answer"=>"Technical and logical puzzles","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Problem type preference indicates career fit."],
["question_text"=>"Which activity would you enjoy most on a weekend?","options"=>["Building an app or coding project","Volunteering at a hospital","Reading about stock markets","Painting or making music"],"correct_answer"=>"Building an app or coding project","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Leisure activities reveal natural career inclinations."],
["question_text"=>"Which work environment suits you best?","options"=>["Tech office with computers and servers","Hospital or research laboratory","Corporate boardroom or trading floor","Design studio or film set"],"correct_answer"=>"Tech office with computers and servers","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Environment preference maps to career domains."],
["question_text"=>"What motivates you most in a career?","options"=>["Building innovative technology","Saving lives and helping patients","Creating wealth and financial success","Expressing creativity and art"],"correct_answer"=>"Building innovative technology","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Core motivation is the strongest career predictor."],
["question_text"=>"Which of these would you most like to be known for?","options"=>["Creating a successful tech product","Discovering a medical breakthrough","Building a successful business empire","Creating art that moves people"],"correct_answer"=>"Creating a successful tech product","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Legacy aspiration reveals deep career values."],
["question_text"=>"How do you prefer to spend your study time?","options"=>["Coding, math problems, and algorithms","Biology, chemistry, and anatomy","Economics, finance, and business cases","Drawing, writing, and creative projects"],"correct_answer"=>"Coding, math problems, and algorithms","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Study preferences directly correlate with career aptitude."],
["question_text"=>"Which news topic interests you most?","options"=>["AI, technology, and startups","Medical research and healthcare","Stock markets and business","Entertainment, fashion, and culture"],"correct_answer"=>"AI, technology, and startups","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"News interests reveal genuine passion areas."],
["question_text"=>"What kind of team would you thrive in?","options"=>["Engineers and developers building products","Doctors and researchers saving lives","Analysts and executives driving business","Designers and creators making content"],"correct_answer"=>"Engineers and developers building products","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Team preference reveals collaborative career fit."],
["question_text"=>"Which skill do you most want to master?","options"=>["Programming and system design","Medical diagnosis and surgery","Financial modeling and investment","Graphic design and storytelling"],"correct_answer"=>"Programming and system design","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Desired skill mastery is a strong career direction indicator."],
["question_text"=>"Which college stream would you choose?","options"=>["B.Tech Computer Science","MBBS Medicine","BBA or MBA Business","B.Des or Fine Arts"],"correct_answer"=>"B.Tech Computer Science","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Stream choice directly maps to career domain."],
["question_text"=>"What kind of impact do you want to make?","options"=>["Revolutionize technology and automation","Improve global health outcomes","Create economic growth and jobs","Inspire people through art and culture"],"correct_answer"=>"Revolutionize technology and automation","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Desired impact reveals career purpose alignment."],
["question_text"=>"Which role sounds most exciting to you?","options"=>["AI Engineer at a top tech company","Surgeon at a leading hospital","Investment Banker at Goldman Sachs","Film Director at a major studio"],"correct_answer"=>"AI Engineer at a top tech company","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Role excitement is a direct career interest indicator."],
["question_text"=>"How do you approach a new project?","options"=>["Research technical solutions and code","Study the problem from a scientific angle","Analyze costs, risks, and returns","Brainstorm creative concepts and designs"],"correct_answer"=>"Research technical solutions and code","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Project approach reveals thinking style and career fit."],
["question_text"=>"Which achievement would make you proudest?","options"=>["Launching a successful tech startup","Developing a life-saving drug","Managing a billion-dollar portfolio","Winning a national design award"],"correct_answer"=>"Launching a successful tech startup","category"=>"Career Interest","difficulty"=>"hard","explanation"=>"Achievement aspiration reveals core career motivation."],
["question_text"=>"What do you do when you have free time?","options"=>["Learn new programming languages or tools","Read medical journals or health articles","Follow financial news and investments","Create art, music, or write stories"],"correct_answer"=>"Learn new programming languages or tools","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Free time activities reveal authentic interests."],
["question_text"=>"Which type of book would you read?","options"=>["Programming, AI, or science fiction","Medical textbooks or biology","Business strategy or finance","Novels, poetry, or art history"],"correct_answer"=>"Programming, AI, or science fiction","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Reading preferences reveal intellectual interests."],
["question_text"=>"Which company would you most want to work at?","options"=>["Google, Microsoft, or Amazon","Apollo Hospitals or AIIMS","Goldman Sachs or McKinsey","Netflix, Spotify, or a creative agency"],"correct_answer"=>"Google, Microsoft, or Amazon","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Company preference directly maps to career domain."],
["question_text"=>"What kind of problems keep you up at night?","options"=>["How to build a better algorithm","How to cure a disease","How to grow a business","How to create something beautiful"],"correct_answer"=>"How to build a better algorithm","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Intrinsic concerns reveal deep career passion."],
["question_text"=>"Which skill comes most naturally to you?","options"=>["Logical thinking and problem solving","Empathy and caring for others","Persuasion and negotiation","Creativity and visual thinking"],"correct_answer"=>"Logical thinking and problem solving","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Natural skills are the strongest predictor of career success."],
["question_text"=>"Which of these would you build if you could?","options"=>["A revolutionary AI application","A new medical treatment","A successful business empire","A masterpiece of art or film"],"correct_answer"=>"A revolutionary AI application","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Build aspiration reveals entrepreneurial career direction."],
["question_text"=>"How do you prefer to communicate?","options"=>["Through data, code, and technical docs","Through patient care and medical reports","Through presentations and negotiations","Through visual design and storytelling"],"correct_answer"=>"Through data, code, and technical docs","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Communication style reveals career domain alignment."],
["question_text"=>"Which course would you take online?","options"=>["Machine Learning on Coursera","Anatomy and Physiology","Financial Modeling in Excel","Graphic Design on Skillshare"],"correct_answer"=>"Machine Learning on Coursera","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Course choice reveals learning interests and career direction."],
["question_text"=>"What is your dream lifestyle?","options"=>["Working at a cutting-edge tech lab","Practicing medicine and saving lives","Running a successful business","Traveling the world as a creative professional"],"correct_answer"=>"Working at a cutting-edge tech lab","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Lifestyle aspiration reveals career-life integration preferences."],
["question_text"=>"Which subject would you teach if you were a teacher?","options"=>["Computer Science and Mathematics","Biology and Health Sciences","Economics and Business Studies","Art, Music, or Literature"],"correct_answer"=>"Computer Science and Mathematics","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Teaching preference reveals deep subject mastery and passion."],
["question_text"=>"Which internship would you choose?","options"=>["Software development at a tech startup","Clinical internship at a hospital","Finance internship at a bank","Design internship at a creative agency"],"correct_answer"=>"Software development at a tech startup","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Internship choice is a direct career interest indicator."],
["question_text"=>"What kind of mentor would you seek?","options"=>["A successful software engineer or CTO","A renowned doctor or researcher","A successful entrepreneur or investor","A famous artist or creative director"],"correct_answer"=>"A successful software engineer or CTO","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Mentor preference reveals role model and career aspiration."],
["question_text"=>"Which problem would you dedicate your life to solving?","options"=>["Making AI accessible to everyone","Eliminating a major disease","Reducing global poverty through business","Making art and culture accessible to all"],"correct_answer"=>"Making AI accessible to everyone","category"=>"Career Interest","difficulty"=>"hard","explanation"=>"Life mission reveals deepest career purpose and values."],
["question_text"=>"Which tool do you enjoy using most?","options"=>["Code editors and development tools","Medical equipment and lab instruments","Spreadsheets and financial software","Design tools like Figma or Photoshop"],"correct_answer"=>"Code editors and development tools","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Tool preference reveals hands-on career domain alignment."],
["question_text"=>"Which achievement in school made you proudest?","options"=>["Winning a coding or math competition","Excelling in biology or science fair","Leading a business or economics project","Winning an art or writing competition"],"correct_answer"=>"Winning a coding or math competition","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Past achievements reveal natural talent and career direction."],
["question_text"=>"How do you handle a difficult challenge?","options"=>["Break it into logical steps and debug","Research medical literature for answers","Analyze costs and find the best ROI","Reimagine it creatively from scratch"],"correct_answer"=>"Break it into logical steps and debug","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Problem-solving approach reveals cognitive style and career fit."],
["question_text"=>"Which YouTube channel would you subscribe to?","options"=>["Tech and programming tutorials","Medical and health education","Finance and investing advice","Art, design, and creative content"],"correct_answer"=>"Tech and programming tutorials","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Content consumption reveals authentic interests."],
["question_text"=>"Which award would mean the most to you?","options"=>["Best Tech Innovator of the Year","Nobel Prize in Medicine","Forbes 30 Under 30 in Business","National Award for Best Film or Art"],"correct_answer"=>"Best Tech Innovator of the Year","category"=>"Career Interest","difficulty"=>"hard","explanation"=>"Award aspiration reveals deepest career values and goals."],
["question_text"=>"Which skill gap worries you most?","options"=>["Not knowing enough programming","Not understanding medical science","Not having enough business acumen","Not being creative enough"],"correct_answer"=>"Not knowing enough programming","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Skill gap anxiety reveals what you value most in your career."],
["question_text"=>"Which project would you be most proud to show?","options"=>["A working app or software system","A medical research paper","A business plan or financial model","A portfolio of creative work"],"correct_answer"=>"A working app or software system","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Portfolio pride reveals authentic career identity."],
["question_text"=>"Which conference would you attend?","options"=>["Google I/O or AWS re:Invent","World Health Summit","Davos Economic Forum","Cannes Film Festival or Design Week"],"correct_answer"=>"Google I/O or AWS re:Invent","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Conference preference reveals professional community alignment."],
["question_text"=>"What kind of data interests you most?","options"=>["Code repositories and system logs","Patient health records and clinical data","Financial statements and market data","User engagement and creative metrics"],"correct_answer"=>"Code repositories and system logs","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Data interest reveals analytical career domain preference."],
["question_text"=>"Which role in a startup would you choose?","options"=>["CTO - Chief Technology Officer","CMO - Chief Medical Officer","CFO - Chief Financial Officer","CCO - Chief Creative Officer"],"correct_answer"=>"CTO - Chief Technology Officer","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Leadership role preference reveals career domain and ambition."],
["question_text"=>"Which skill would you teach your younger sibling?","options"=>["How to code and build apps","How to stay healthy and understand biology","How to manage money and invest","How to draw, write, or make music"],"correct_answer"=>"How to code and build apps","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Teaching preference reveals what you value and know best."],
["question_text"=>"Which movie genre do you enjoy most?","options"=>["Sci-fi and technology thrillers","Medical dramas and documentaries","Business and financial thrillers","Artistic films and creative documentaries"],"correct_answer"=>"Sci-fi and technology thrillers","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Entertainment preference reveals subconscious career interests."],
["question_text"=>"Which social media content do you create or consume most?","options"=>["Tech tutorials and coding tips","Health and wellness advice","Business and finance insights","Creative art and entertainment"],"correct_answer"=>"Tech tutorials and coding tips","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Content creation reveals authentic expertise and passion."],
["question_text"=>"Which global challenge excites you to work on?","options"=>["Building AI for climate change solutions","Developing vaccines for new diseases","Creating economic opportunities in developing nations","Using art to bridge cultural divides"],"correct_answer"=>"Building AI for climate change solutions","category"=>"Career Interest","difficulty"=>"hard","explanation"=>"Global challenge preference reveals career purpose at scale."],
["question_text"=>"Which skill makes you stand out among friends?","options"=>["Technical problem-solving and coding","Medical knowledge and health advice","Financial planning and business ideas","Creative thinking and artistic talent"],"correct_answer"=>"Technical problem-solving and coding","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Peer-recognized skills reveal natural career strengths."],
["question_text"=>"Which part of a product excites you most?","options"=>["The backend architecture and algorithms","The safety and health impact on users","The business model and revenue strategy","The visual design and user experience"],"correct_answer"=>"The backend architecture and algorithms","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Product focus reveals functional career domain preference."],
["question_text"=>"Which certification would you pursue first?","options"=>["AWS Cloud Practitioner or Google ML","USMLE or medical board certification","CFA or CA qualification","Adobe Certified Professional or design cert"],"correct_answer"=>"AWS Cloud Practitioner or Google ML","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Certification choice reveals career investment priorities."],
["question_text"=>"Which type of research excites you?","options"=>["AI and computer science research","Medical and pharmaceutical research","Economic and market research","Cultural and artistic research"],"correct_answer"=>"AI and computer science research","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Research interest reveals intellectual career domain."],
["question_text"=>"Which city would you most want to work in?","options"=>["Bangalore or San Francisco for tech","Boston or London for medicine","Mumbai or New York for finance","Paris or Mumbai for creative industries"],"correct_answer"=>"Bangalore or San Francisco for tech","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"City preference reveals career ecosystem alignment."],
["question_text"=>"Which skill do you practice in your spare time?","options"=>["Coding personal projects or learning new tech","First aid, fitness, or health research","Tracking investments or reading business news","Photography, writing, or making videos"],"correct_answer"=>"Coding personal projects or learning new tech","category"=>"Career Interest","difficulty"=>"easy","explanation"=>"Spare time practice reveals authentic career passion."],
["question_text"=>"Which type of company culture fits you?","options"=>["Fast-paced tech startup with innovation","Mission-driven healthcare organization","High-performance investment bank","Creative agency with artistic freedom"],"correct_answer"=>"Fast-paced tech startup with innovation","category"=>"Career Interest","difficulty"=>"medium","explanation"=>"Culture fit reveals career environment preference."],
["question_text"=>"In 10 years, where do you see yourself?","options"=>["Leading a tech team or founding a startup","Practicing as a specialist doctor or researcher","Managing investments or running a business","Creating award-winning art or media content"],"correct_answer"=>"Leading a tech team or founding a startup","category"=>"Career Interest","difficulty"=>"hard","explanation"=>"10-year vision is the strongest predictor of career direction."],
];

foreach ($interestQuestions as $q) {
    App\Models\Question::create($q);
}
echo "Added " . count($interestQuestions) . " interest questions. Total: " . App\Models\Question::count();

